export const START_GAME = 'START_GAME';

export const SET_PLACED_TILES = 'SET_PLACED_TILES';

export const ADD_SELECTED_TILE = 'ADD_SELECTED_TILE';
export const REMOVE_SELECTED_TILE = 'REMOVE_SELECTED_TILE';
export const CLEAR_SELECTED_TILES = 'CLEAR_SELECTED_TILES';

export const SET_PENDING_TILES = 'SET_PENDING_TILES';
export const REMOVE_PENDING_TILES = 'REMOVE_PENDING_TILES';

export const APPEND_REMOVED_TILES = 'APPEND_REMOVED_TILES';
export const CLEAR_REMOVED_TILES = 'CLEAR_REMOVED_TILES';

export const INCREMENT_SCORE = 'INCREMENT_SCORE';

export const SET_MESSAGE = 'SET_MESSAGE';
